### ISSUE TITLE
TypeError: Cannot read property 'sort' of undefined

### ISSUE THREAD

**Issue by zwhitchcox** [JacksonGariety/gulp-nodemon#102]
Having an error using nodemon with browser-sync
```sh
/home/ec2-user/dash/node_modules/nodemon/lib/monitor/match.js:132
  var rules = monitor.sort(function (a, b) {
                     ^

TypeError: Cannot read property 'sort' of undefined
    at match (/home/ec2-user/dash/node_modules/nodemon/lib/monitor/match.js:132:22)
    at FSWatcher.filterAndRestart (/home/ec2-user/dash/node_modules/nodemon/lib/monitor/watch.js:124:19)
    at emitTwo (events.js:87:13)
    at FSWatcher.emit (events.js:172:7)
    at FSWatcher.<anonymous> (/home/ec2-user/dash/node_modules/chokidar/index.js:171:15)
    at FSWatcher._emit (/home/ec2-user/dash/node_modules/chokidar/index.js:208:5)
    at FSWatcher.NodeFsHandler._handleFile (/home/ec2-user/dash/node_modules/chokidar/lib/nodefs-handler.js:275:10)
    at FSWatcher.<anonymous> (/home/ec2-user/dash/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

my gulpfile:

```js
 // the server is not here
  4 // check out bin/www
  5
  6 const gulp    = require('gulp')
  7 const replace = require('gulp-replace')
  8 const zip     = require('gulp-zip')
  9
 10 const browserSync = require('browser-sync')
 11 const nodemon     = require('gulp-nodemon')
 12
 13 gulp
 14   .task('zip:lambda:test', function() {
 15     gulp
 16       .src(['Lambda/Lambda_Teradata/**'])
 17       .pipe(replace(/__DATABASE_TYPE__/g,'\'MulesoftTest\''))
 18       .pipe(zip('MulesoftTest.zip'))
 19       .pipe(gulp.dest('build'))
 20   })
 21
 22 gulp.task('serve', ['nodemon'],()=> {
 23   return browserSync.init(null, {
 24     proxy: 'http://localhost:3000',
 25     files: ['public/**'],
 26     port: 4000
 27   })
 28 })
 29
 30 gulp.task('reload',['nodemon'],()=> {
 31   browserSync.reload()
 32 })
 33
 34 gulp.task('nodemon', (cb) => {
 35   try { return nodemon({
 36     script: 'app.js',
 37     env: { 'PORT':3000},
 38     files: ['**']
 39   }).on('start', () => {
 40       cb()
 41   })
 42   } catch (e) {
 43     cb()
 44   }
 45 })
 46
 47 gulp.task('default',['serve'],()=>{
 48   gulp.watch('public/**',['reload'])
 49 })
 ```

**Comment by JacksonGariety** [comment]
If you're using nodemon as a way to "start" the app and then immediately trying to "kill" it by calling `cb()` while gulp watch runs in the background you're misunderstanding the purpose of nodemon.

Assuming that's the case, you can solve your issue by getting rid of `gulp-watch` and adding this to your nodemon config

```javascript
nodemon({
  ...
}).on('restart', browserSync.reload)
```

Or you can get rid of nodemon and use `gulp-bash` to start the app.
