### ISSUE TITLE
Error: Timeout must be a number!

### ISSUE THREAD

**Issue by viglucci** [JacksonGariety/gulp-nodemon#125]
Updating to version 2.2.0 from ^2.0.2 causes the below error to be emitted constantly when watching with gulp-watch. Reverting to gulp-nodemon@2.1.0 seems to be working as expected.

I see that gulp-watch also published 4.3.10 (which we are running) the same day as gulp-nodemon@2.2.0, is this related?

```
Message:
    Timeout must be a number!
Stack:
Error: Timeout must be a number!
    at Function.script.emit (c:\dev\project-name\node_modules\gulp-nodemon\index.js:94:13)
    at reloadServer (c:\dev\project-name\gulp\tasks\development.js:58:10)
    at wrappedMapper (c:\dev\project-name\node_modules\event-stream\node_modules\map-stream\index.js:84:19)
    at Stream.stream.write (c:\dev\project-name\node_modules\event-stream\node_modules\map-stream\index.js:96:21)
    at Duplex.ondata (c:\dev\project-name\node_modules\gulp-watch\node_modules\readable-stream\lib\_stream_readable.js:542:20)
    at emitOne (events.js:77:13)
    at Duplex.emit (events.js:169:7)
    at readableAddChunk (c:\dev\project-name\node_modules\gulp-watch\node_modules\readable-stream\lib\_stream_readable.js:213:18)
    at Duplex.Readable.push (c:\dev\project-name\node_modules\gulp-watch\node_modules\readable-stream\lib\_stream_readable.js:172:10)
    at Duplex._write (c:\dev\project-name\node_modules\gulp-watch\index.js:66:8)
```

**Comment by JacksonGariety** [comment]
@viglucci would you mind posting the relevant lines from your Gulpfile?

**Comment by JacksonGariety** [comment]
@IOAyman I think that the emit shim traded backward-compatibility with node's EventEmitter class (the `timeoutInSecs`). I'm going to revert it until we come up with a solution that won't break existing code.

I have a feeling that viglucci's code looks like this:

    stream.emit('event a', 'event b', 'event c')

**Comment by IOAyman** [comment]
@JacksonGariety Noted. I'll push a quick fix in a PR

**Comment by viglucci** [comment]
@JacksonGariety bumping to gulp-nodemon@2.2.1 seems to be working as expected.

Unfortunately I am not at liberty to share source, however we are using the `run-sequence` module to run a combination of tasks in series and in parallel that are separated into different module files. One of such task starts nodemon and exports a function which calls `require("event-stream").map(callback)` where callback calls `server.emit` (where server is a instance of nodemon) with the second argument as a string filename / path. The exported function is executed by a independent task which is watching source and streams files on change using gulp-watch.

Thanks for addressing this.
