### ISSUE TITLE
nodemon is calling all gulp tasks on restart

### ISSUE THREAD

**Issue by dougnukem** [JacksonGariety/gulp-nodemon#15]
I'm trying to listen to the on('restart') event of nodemon and have it run a specific gulp task, but it seems to be running ALL the gulp tasks.

I'm running node 0.10.25, gulp 3.5.2, and gulp-nodemon 0.1.2.

For example with this gulp file:

```
var gulp = require('gulp'),
    nodemon = require('gulp-nodemon'),
    gutil = require('gulp-util');

var livereloader = function () {
    gutil.log('[livereoload called]');
};
gulp.task('livereload', livereloader);

var linter = function() {
  gutil.log('[lint called]');
};
gulp.task('lint', linter);

var tester = function() {
  gutil.log('[test called]');
};
gulp.task('test', tester);

gulp.task('develop', function () {
  nodemon({ script: 'index.js', options: '-e html,js -i ignored.js' })
    .on('restart', ['lint']);
});
```

When I run `gulp develop` and then modify a file or type "rs" to force a restart I see the following:

```
$ gulp develop
[gulp] Using file /Users/ddaniels/code/github/gulp-apps/gulp-nodemon-issue/gulpfile.js
[gulp] Working directory changed to /Users/ddaniels/code/github/gulp-apps/gulp-nodemon-issue
[gulp] Running 'develop'...
[gulp] Finished 'develop' in 1.59 ms
[nodemon] v1.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
SERVER RUNNING PORT 8080
rs
gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
[gulp] Running 'livereload'...
[gulp] [livereoload called]
[gulp] Finished 'livereload' in 388 μs
[gulp] Running 'lint'...
[gulp] [lint called]
[gulp] Finished 'lint' in 217 μs
[gulp] Running 'test'...
[gulp] [test called]
[gulp] Finished 'test' in 146 μs
[gulp] Running 'develop'...
[gulp] Finished 'develop' in 768 μs
[nodemon] starting `node index.js`
[nodemon] v1.0.14
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
SERVER RUNNING PORT 8080
SERVER RUNNING PORT 8080

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at Function.app.listen (/Users/ddaniels/code/github/gulp-apps/gulp-nodemon-issue/node_modules/connect/lib/proto.js:232:24)
    at Object.<anonymous> (/Users/ddaniels/code/github/gulp-apps/gulp-nodemon-issue/index.js:5:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

I've also tried specifying it like this:

```
gulp.task('develop', function () {
    nodemon({
        script: 'index.js',
        options: '-e html,js -i ignored.js'
    }).on('restart', function(){
        gutil.log('[nodemon]', 'Restarted', gutil.colors.cyan('123'));
        livereloader();
    });
});
```

If I remove the `options: '-e html,js -i ignored.js'` it seems to properly call the restart handler or tasks specified by string.

**Comment by azat-co** [comment]
I was getting these crashes with listen EADDRINUSE and gulp-nodemon 2.0.3

My gulpfile looked like this (mostly from the readme):

```
gulp.task('develop', function (done) {
  nodemon({ script: 'index.js',
    ext: 'html js',
    ignore: ['ignored.js'],
    tasks: [] })
});
```

I removed the options and it worked.

```
gulp.task('develop', function (done) {
  nodemon({ script: 'index.js'})
})
```

**Comment by Zane-XY** [comment]
Same error while using gulp-nodemon 2.0.3
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
```

```javascript
gulp.task('develop', function () {
	nodemon({
		script: 'app.js',
		ext: 'es6 js handlebars', // extension watch list, changes trigger restart
		execMap: {
			"js": "babel-node --stage 0"
		},
		tasks: function (changedFiles) {
			var tasks = []
			changedFiles.forEach(function (file) {
				if (path.dirname(file).indexOf('client') >= 0 && !~tasks.indexOf('build-dev')) tasks.push('build-dev')
			});
			return tasks;
		}
	});
});
```
