### ISSUE TITLE
The rs command sometimes causes a pipe error.

### ISSUE THREAD

**Issue by Beanow** [JacksonGariety/gulp-nodemon#54]
When repeatedly issuing `rs` command using stdin, in some random occasions there seems to be a race condition that crashes the gulp task.

```sh
[gulp] [nodemon] starting `node ./lib/api/index.js`
rs
[gulp] [nodemon] starting `node ./lib/api/index.js`
rs
[gulp] [nodemon] starting `node ./lib/api/index.js`
rs
[gulp] [nodemon] starting `node ./lib/api/index.js`
rs

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: read ECONNRESET
  at errnoException (net.js:901:11)
  at Pipe.onread (net.js:556:19)
```

**Comment by JacksonGariety** [comment]
@Beanow very interesting bug. I can't reproduce this, can you give me some detailed steps or is it jsut sporadic?

**Comment by Beanow** [comment]
It is sporadic I'm afraid. Try using a small application that doesn't take long to load and repeatedly reload it. Although I'm not sure what more information that would give you.
