### ISSUE TITLE
Fails on change when no tasks specified in gulpfile

### ISSUE THREAD

**Issue by nubs** [JacksonGariety/gulp-nodemon#65]
The original start of the service works, but when I touch a file, gulp-nodemon crashes:
```
/path/to/node_modules/gulp-nodemon/index.js:73
    if (!(tasks instanceof Array)) throw new Error('Expected task name or arra
                                         ^
Error: Expected task name or array but found: undefined
    at run (/path/to/node_modules/gulp-nodemon/index.js:73:42)
    at null.<anonymous> (/path/to/node_modules/gulp-nodemon/index.js:29:9)
    at EventEmitter.emit (events.js:117:20)
    at log (/path/to/node_modules/gulp-nodemon/node_modules/nodemon/lib/utils/log.js:20:7)
    at restartBus (/path/to/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:231:13)
    at filterAndRestart (/path/to/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:273:16)
    at /path/to/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:291:9
    at /path/to/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:100:9
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)

```

**Comment by konsti** [comment]
Same for me

**Comment by lucasmotta** [comment]
+1

**Comment by manonthemat** [comment]
I confirm this behavior in gulp-nodemon version 2.0.0

**Comment by jpetitcolas** [comment]
+1

**Comment by JacksonGariety** [comment]
@nubs not getting this one, may I see a sample gulpfile to debug?

**Comment by lsiden** [comment]
I have 2.0.3 but this is still occurring.  Here's a full trace of my brief session:

    lsiden@morpheus [cpservice] (master $) [1]$ gulp serve
    [17:13:11] Warning: gulp version mismatch:
    [17:13:11] Global gulp is 3.9.0
    [17:13:11] Local gulp is 3.8.11
    [17:13:11] Using gulpfile ~/pah/pahpublicbuild/cpservice/gulpfile.js
    [17:13:11] Starting 'serve'...
    [17:13:11] Finished 'serve' after 4.65 ms
    [17:13:11] [nodemon] v1.3.7
    [17:13:11] [nodemon] to restart at any time, enter `rs`
    [17:13:11] [nodemon] watching: *.*
    [17:13:11] [nodemon] starting `node bin/www`
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: listen EADDRINUSE
        at exports._errnoException (util.js:746:11)
        at Server._listen2 (net.js:1156:14)
        at listen (net.js:1182:10)
        at Server.listen (net.js:1267:5)
        at EventEmitter.app.listen (/home/lsiden/pah/pahpublicbuild/cpservice/node_modules/express/lib/application.js:595:24)
        at Object.<anonymous> (/home/lsiden/pah/pahpublicbuild/cpservice/bin/www:7:18)
        at Module._compile (module.js:460:26)
        at Object.Module._extensions..js (module.js:478:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
    [17:13:11] [nodemon] app crashed - waiting for file changes before starting...
    [17:13:12] /home/lsiden/pah/pahpublicbuild/cpservice reloaded.
    [17:13:22] [nodemon] restarting due to changes...
    [17:13:22] [nodemon] starting `node bin/www`
    /home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/index.js:73
        if (!(tasks instanceof Array)) throw new Error('Expected task name or arra
                                             ^
    Error: Expected task name or array but found: [object Object]
        at run (/home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/index.js:73:42)
        at null.<anonymous> (/home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/index.js:58:22)
        at emit (events.js:129:20)
        at restartBus (/home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:240:7)
        at filterAndRestart (/home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:273:16)
        at /home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:291:9
        at /home/lsiden/pah/pahpublicbuild/cpservice/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:100:9
        at ChildProcess.exithandler (child_process.js:742:7)
        at ChildProcess.emit (events.js:110:17)
        at maybeClose (child_process.js:1015:16)
    lsiden@morpheus [cpservice] (master $) [1]$

**Comment by lsiden** [comment]
I finally narrowed it down to livereload.  See my comment here: https://github.com/vohof/gulp-livereload/issues/28#issuecomment-122330533
