### ISSUE TITLE
Nodemon crashes when used with Browser Sync

### ISSUE THREAD

**Issue by Snugug** [JacksonGariety/gulp-nodemon#86]
I'm trying to proxy my nodemon served server through Browser Sync for development purposes. Running either my Browser Sync process or my Nodemon process works fine, but when run together Nodemon crashes. I'm using `gulp 3.9.0`, `gul-nodemon 2.0.3`, and `browser-sync 2.8.2`

**Gulpfile.js**
```javascript
'use strict';

var gulp = require('gulp'),
    nodemon = require('gulp-nodemon'),
    browserSync = require('browser-sync').create();

gulp.task('nodemon', function (cb) {
  console.log('Nodemon');
  return nodemon({
    'script': 'index.js'
  })
  .once('start', function () {
    console.log('Foo');
    cb();
  })
  .on('restart', function () {
    console.log('Restarted!');
  });
});

gulp.task('browser-sync', ['nodemon'], function () {
  console.log('Browser Sync');
  browserSync.init({
    'proxy': 'localhost:3000'
  });
});

gulp.task('default', ['browser-sync']);
```

**Error**
```bash
child_process.js:788
  child.stdout.addListener('data', function(chunk) {
              ^
TypeError: Cannot read property 'addListener' of undefined
    at Object.exports.execFile (child_process.js:788:15)
    at exports.exec (child_process.js:649:18)
    at changeFunction ({{path}}/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:93:7)
    at module.exports [as _onTimeout] ({{path}}/node_modules/gulp-nodemon/node_modules/nodemon/lib/monitor/watch.js:293:5)
    at Timer.listOnTimeout (timers.js:119:15)
````

**Comment by Snugug** [comment]
Resolved this by explicitly only watching the files I need for my server
