### ISSUE TITLE
Waiting for tasks to get done

### ISSUE THREAD

**Issue by rodoabad** [JacksonGariety/gulp-nodemon#96]
Assume the following tasks.

```javascript

task('linting')

task('clean', ['linting'])

task('compile', ['clean'])

task('watch')

task('build', ['compile', 'watch'])
```

```javascript
task('run', ['build'], () => {

  nodemon({
    script: 'dist/server.js',
    watch: [
      'src'
    ]
  });

});
```

As far as gulp is concerned `run` won't even run until `build` is done.

When looking at my logs, this is what happens (log below).

```javascript
[12:12:04] Requiring external module babel-core/register
[12:12:10] Using gulpfile d:\Web\GitHub\es6-hapijs-seed\gulpfile.babel.js
[12:12:10] Starting 'linting'...
[12:12:10] Finished 'linting' after 34 ms
[12:12:10] Starting 'clean'...
[12:12:10] Finished 'clean' after 2.4 ms
[12:12:10] Starting 'compile'...
[12:12:10] Finished 'compile' after 2.46 ms
[12:12:10] Starting 'watch'...
[12:12:11] Finished 'watch' after 8.13 ms
[12:12:11] Starting 'build'...
[12:12:11] Finished 'build' after 7.46 μs
[12:12:11] Starting 'run'...
[12:12:11] Finished 'run' after 1.48 ms
[12:12:11] [nodemon] 1.8.0
[12:12:11] [nodemon] to restart at any time, enter `rs`
[12:12:11] [nodemon] watching: d:\Web\GitHub\es6-hapijs-seed\src/**/*
[12:12:11] [nodemon] starting `node dist/server.js`
module.js:338
    throw err;
    ^

Error: Cannot find module 'd:\Web\GitHub\es6-hapijs-seed\dist\server.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
[12:12:11] [nodemon] app crashed - waiting for file changes before starting...
```

But you can see that nodemon will try and run `dist/server.js` and then throw an error because it couldn't find it.

Adding `build` to nodemon's `tasks` solves this problem.

```javascript
gulp.task('run', ['build'], () => {

  nodemon({
    tasks: [
      'build'
    ],
    script: 'dist/server.js',
    watch: [
      'src'
    ]
  });

});
```

But why do I have add `build` again when `build` must finish first before `run` starts in the first place?

**Comment by rodoabad** [comment]
Just adding more logs.

```javascript
Server running at: http://localhost:8000
[17:16:10] [nodemon] restarting due to changes...
[17:16:10] Starting 'lint'...
[17:16:10] Finished 'lint' after 152 ms
[17:16:10] Starting 'clean'...
[17:16:10] [nodemon] starting `node dist/server.js`
[17:16:10] Finished 'clean' after 6.41 ms
[17:16:10] Starting 'compile'...
[17:16:10] Finished 'compile' after 42 ms
Server running at: http://localhost:8000
```

**Comment by JacksonGariety** [comment]
@rodoabad putting it in the `tasks` array ought to run it first, so you should be able to compile your app there.

This is a bit out-of-the-way by Gulp standards, which is why this is listed as gulp-friendly rather than a true gulp plugin. The way Gulp is setup, there's no good way to integrate it with nodemon, so the tasks array is the core of this project.
